version: '3'
services:
  ollama:
    build:
      context: .
      dockerfile: ollama.Dockerfile
    volumes:
      - ./data/ollama:/root/.ollama
    pull_policy: always
    ports:
      - "11434:11434"
    restart: always
    networks:
      - docker_net
  mathcal_app:
    build:
      context: .
      dockerfile: mathcal_app.Dockerfile
      args:
        BASE_IMAGE: "python:3.12-bullseye"
    volumes:
      - .:/app
    ports:
      - "38080:38080"
    restart: unless-stopped
    networks:
      - docker_net
networks:
  docker_net:
    driver: bridge
